### ISSUE TITLE
lvm is broken

### ISSUE THREAD

**Issue by irevoire** [open-switch/opx-docs#26] opened 2019-06-18 14:34 UTC
Hello,

I'm following this tutorial: https://github.com/open-switch/opx-docs/wiki/Run-virtual-machine
I have installed a clean ubuntu 16.04, then I installed virtualbox. And when I run `lvm create openswitch` this is what I got:
```

Getting OS-Installer via URL. Downloading.... Please wait!
Time remaining: 00:00:00  100% [====================================>] 405 / 405

OS-installer file: /home/irevoire/PKGS_OPX-stable-jessie-installer-x86_64.bin
Getting ONIE-Recovery via URL. Downloading.... Please wait!
Time remaining: 00:00:00  100% [==========================>] 17934336 / 17934336

ONIE-Recovery file: /home/irevoire/onie_kvm.iso
Deleting VM name: "openswitch"
Initial boot in progress........................................................OK
ONIE is self-embedding..........................................................OK
Wait for VM to boot.............................................................OK
ONIE stop discovery.............................................................OK
Load OS-installer. This operation may take a few minutes. Please wait...........OK
Installing OS...................................................................OK
Failed to detect OS installed paritions. Please verify nos installer package is valid. /installer: line 1: syntax error: unexpected newline
Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
Connection to 127.0.0.1 closed.
```

**Comment by jghalam** [comment] 2019-06-19 03:14
Hi,
The log shows that you're using jessie installer. I think the issue is
related to the pointer to the "stable" version of OPX. The stable should be
pointing to the latest, which is 3.2.0 installer and it is Stretch based.

We will get the stable link updated to point to the right installer.

Meanwhile, you can use the following command to create a VM:

$ ./lvm create openswitch --bin
http://archive.openswitch.net/installers/3.2.0/Dell-EMC/PKGS_OPX-3.2.0.9999-rc0-installer-x86_64.bin

I tried the above command on my 16.04 Ubuntu and it worked. Please let me
know how it goes for you.

Thanks,
Joe

**Comment by jeff-yin** [comment] 2019-06-20 17:20
I think the issue has been resolved, so I will close the issue for now. Feel free to reopen if you run into additional issues relating to this topic.

**Closed by jeff-yin** 2019-06-20 17:20 UTC
Labels: triage
